== Basic Extensions

There is a couple of basic extensions that are developed alongside the core Revapi library. These are by default
available when using the Revapi's maven plugin or using Revapi standalone. If you're using Revapi on your own, you need
to explicitly put the `revapi-basic-features-XXX.jar` on your class path, or depend on
`org.revapi:revapi-basic-features:XXX` maven artifact (where XXX is the version).

== Examples

=== Classification Transformation
By configuring this extension you can reclassify certain differences to have different classification. This can be used
to reclassify problems as less or more severe according to the policies that you want to apply.

For example, by specifying the following configuration:

```javascript
{
    "revapi" : {
        "reclassify" : {
            "code" : "java.class.added",
            "new" : "class my.great.app.ForbiddenClass",
            "classify" : {
                "BINARY" : "BREAKING"
            }
        }
    }
}
```

it will be an API error if the class `my.great.app.ForbiddenClass` appears in the new version of a java library (granted
this rule is somewhat weird and maybe not entirely useful, but it illustrates the purpose - you can come up with
different policies that your code should follow and enforce them through such rules).

More in the link:apidocs/org/revapi/basic/ClassificationTransform.html[javadoc].

=== Configurable Element Filter
This can be used to leave certain API elements out from the analysis.

For example, by specifying the following configuration:

```javascript
{
    "revapi" : {
        "filter" : {
            "elements": {
                "exclude" : ["class my\\.great\\.app\\..*\\.impl\\..*"]
            },
            "archives": {
                "include" : ["com\\.acme:acme-foo:.*"]
            }
        }
    }
}
```

all the java classes in any of the `impl` packages under `my.great.app` package will be excluded from API checking.
In addition, the analysis will only check elements from the archive specified archive. In this example we're
supposing the configuration is for the maven plugin which recognizes archives by GAVs. In the example therefore we're
limiting the checks to the archive with the `groupId` `com.acme` and `artifactId` `acme-foo` in any packaging type
and version.

The `exclude` and `include` configuration properties are arrays of regular expressions for matching the elements.

More in the link:apidocs/org/revapi/basic/ConfigurableElementFilter.html[javadoc].

=== Ignore Differences
This can be used to ignore certain differences before they are sent to the reporters for final output.

For example, by specifying the following configuration:

```javascript
{
    "revapi" : {
        "ignore" : [
            {
                "code" : "java.method.addedToInterface",
                "new" : "class my.great.app.Context",
                "justification" : "I thought this would be a good idea."
            }
        ]
    }
}
```

any new method in the `my.great.app.Context` java interface will not be reported as an API breakage. While adding a
new method to an interface is generally a breaking change, because any implementation of such interface that would not
have such new method would become invalid, this can be OK if you control all the implementations of the interface and
don't allow or support user implementations of it. A nice link:../revapi-java/enhance-java-checks.html[example] are
Java's EJB interfaces - these are used by the users to invoke methods on your EJBs but the users aren't supposed to
implement those interfaces, merely use them.

More in the link:apidocs/org/revapi/basic/IgnoreDifferenceTransform.html[javadoc].
