== Basic Extensions

There is a couple of basic extensions that are developed alongside the core Revapi library. These are by default
available when using the Revapi's maven plugin or using Revapi standalone. If you're using Revapi on your own, you need
to explicitly put the `revapi-basic-features-XXX.jar` on your class path, or depend on
`org.revapi:revapi-basic-features:XXX` maven artifact (where XXX is the version).

=== Classification Transformation
By configuring this extension you can reclassify certain differences to have different classification. This can be used
to reclassify problems as less or more severe according to the policies that you want to apply.

More on the link:extensions/reclassify.html[detail page] or in the
link:apidocs/org/revapi/basic/ClassificationTransform.html[javadoc].

=== Configurable Element Filter
This can be used to leave certain API elements out from the analysis.

More on the link:extensions/filter.html[detail page] or in the
link:apidocs/org/revapi/basic/ConfigurableElementFilter.html[javadoc].

=== Ignore Differences
This can be used to ignore certain differences before they are sent to the reporters for final output.

More on the link:extensions/ignore.html[detail page] or in the
link:apidocs/org/revapi/basic/IgnoreDifferenceTransform.html[javadoc].
