= Revapi
:toc:

image:https://github.com/revapi/revapi/actions/workflows/build.yml/badge.svg[Build Status, link=https://github.com/revapi/revapi/actions/workflows/build.yml]
image:https://codecov.io/github/revapi/revapi/coverage.svg?branch=main[Code Coverage,link=https://codecov.io/github/revapi/revapi?branch=main]

https://revapi.org[Revapi] is a tool for API analysis and change tracking.

== Summary

While Revapi is designed to be extensible and in theory should support API checks in other languages
than Java (not just programming languages but anything that can be decomposed to a tree structure)
the only extension in existence today is the Java API checker.

The main distinguishing features of the Java API checker include:

* large number of https://revapi.org/revapi-java/differences.html[API checks]
** categorized by their influence on source, binary and "semantic" compatibility
* support for computing the API "surface" by tracking usages of types across the checked library
and also its dependencies (ability to report type "leakage" from deps)
* powerful filtering of elements to check and reclassification of found problems
* ability to filter by annotation presence
* Maven plugin automatically includes dependencies in the check

Other features:

* ability to judge the severity of changes based on semver rules (see
https://revapi.org/revapi-basic-features/versions.html[here])
* automatic updates of pom.xml or release.properties versions according to semver rules (see 
https://revapi.org/revapi-maven-plugin/specifying-versions.html[here])
* pluggable reporting (standard output, maven site generation, https://revapi.org/revapi-reporter-text/index.html[FreeMarker templates], https://revapi.org/revapi-reporter-json/index.html[JSON], ...)

== Building

This is a maven project, so to build you simply:

 mvn install

== Usage

Revapi can be invoked in a couple of ways. It can be used as a standalone program, 
as a maven plugin or it can also be embedded in your application and used as a library.

=== Standalone

https://revapi.org/revapi-site/downloads.html[Download] the standalone distribution zip and

 unzip revapi-XXX-standalone.zip
 cd revapi-XXX-standalone
 ./revapi.sh

Read the usage info and go.

=== Maven

[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.revapi</groupId>
            <artifactId>revapi-maven-plugin</artifactId>
            <version>...</version>
            <dependencies>
                <dependency>
                    <groupId>org.revapi</groupId>
                    <artifactId>revapi-java</artifactId>
                    <version>...</version>
                </dependency>
                <dependency>
                    <groupId>com.acme</groupId>
                    <artifactId>my-extension</artifactId>
                    <version>...</version>
                </dependency>
                ...
            </dependencies>
            <configuration>
                ...
            </configuration>
            <executions>
                <execution>
                    <id>api-check</id>
                    <goals><goal>check</goal></goals>
                    ...
                </execution>
                ...
            </executions>
        </plugin>
        ...
    </plugins>
    ...
</build>
----

=== Gradle

There is an external Gradle plugin available for Revapi, https://github.com/palantir/gradle-revapi.

=== Embedding

[source,java]
----
Revapi revapi = Revapi.builder().withAllExtensionsFromThreadContextClassLoader().build();

AnalysisContext analysisContext = AnalysisContext.builder()
    .withOldAPI(API.of(...))
    .withNewAPI(API.of(...))
    .withConfigurationFromJSON("json").build();

revapi.analyze(analysisContext);
----

== Extending Revapi

See the https://revapi.org/revapi/architecture.html[site] for more info.

== Getting in touch

Mastodon:: https://botsin.space/@revapi[@revapi@botsin.space]
Twitter:: https://twitter.com/revapi_org[@revapi_org]
Matrix:: #revapiorg:matrix.org
Mailing list:: https://groups.google.com/forum/#!forum/revapi[revapi@googlegroups.com]
Issues:: https://github.com/revapi/revapi/issues
Code:: https://github.com/revapi/
