= YAML Analyzer

The YAML analyzer is a very simple analyzer of YAML files based on the xref:revapi-jackson::index.adoc[].

== Configuration

This analyzer only provides the xref:revapi-jackson::index.adoc#_configuration[configuration properties] of the base
jackson analyzer.

=== Examples
To analyze a file encoded in UTF-16, you can use the following configuration:

[source,xml]
....
<revapi.json>
    <charset>UTF-16</charset>
</revapi.json>
....

To look for a specific file (META-INF/config.yaml) with in ZIPs that are provided as archives, you can do this:
[source,xml]
....
<revapi.json>
    <pathRegex>/META-INF/config\.yaml</pathRegex>
</revapi.json>
....

== Detected differences

There is not much this analyzer can detect in the YAML files - merely additions, removals and changes.

[[yaml.added]]
=== YAML node added - `yaml.added`
[cols="35s,<65d"]
|=============
| Binary severity   | NA
| Source severity   | NA
| Semantic severity | potentially breaking
|=============

This is reported on YAML nodes that have been added in the new version of the API (the file).
Primitive values, object nodes, array nodes as well as individual elements within the objects
or arrays are supported.

[options=header]
|====
2+| Match parameters
| `file` | the file (if within a ZIP archive) in which the difference has been found
| `path` | the JSON path to the added element within the file
|====

[[yaml.removed]]
=== YAML node removed - `yaml.removed`
[cols="35s,<65d"]
|=============
| Binary severity   | NA
| Source severity   | NA
| Semantic severity | breaking
|=============

This is reported on YAML nodes that have been removed from the new version of the API (the file).
Primitive values, object nodes, array nodes as well as individual elements within the objects
or arrays are supported.

[options=header]
|====
2+| Match parameters
| `file` | the file (if within a ZIP archive) in which the difference has been found
| `path` | the JSON path to the added element within the file
|====

[[yaml.changed]]
=== YAML node changed - `yaml.changed`
[cols="35s,<65d"]
|=============
| Binary severity   | NA
| Source severity   | NA
| Semantic severity | potentially breaking
|=============

This is reported on YAML nodes that have been changed in the new version of the API (the file).
Primitive values, object nodes, array nodes as well as individual elements within the objects
or arrays are supported.

[options=header]
|====
2+| Match parameters
| `file` | the file (if within a ZIP archive) in which the difference has been found
| `path` | the JSON path to the added element within the file
| `oldValue` | the value as it was present in the old version
| `newValue` | the value as it is present in the new version
|====
