== Regression Fixes
:docname: 20180523-fixes

After the last week's new releases a regression has been discovered which warranted a quick new release.

So without further ado, here's what's new:

The new version of `revapi-java`, `0.17.1`, fixes a regression caused by the speed ups from `0.17.0` where methods and
fields inherited from super classes from other archives can pop up in the found problems even if the inheriting classes
were filtered out.

Additionally, `revapi-java-0.17.1` add the `oldArchive` and `newArchive` attachments to the found differences. This
enables users to filter the found differences by the archive they're originating from. People can use that to set up
filtering of problems coming from other modules of a multi-module build similarly to what is described in
https://github.com/revapi/revapi/pull/133#issuecomment-391062799[this comment].

There is also a new release of the maven plugin, `revapi-maven-plugin-0.10.3` that fixes a long standing bug in the
goals that modify the versions in `pom.xml`. These goals would malfunction when the `revapi.semver.ignore` extension was
enabled.

include::../util/disqus.adoc[]
