= Revapi API

image:https://travis-ci.org/revapi/revapi-api.svg[Build Status,link=https://travis-ci.org/revapi/revapi-api]

This is the main API of Revapi, the API evolution checker.

== About Revapi

Revapi is a build tool that strives for easy integration of API evolution checks into the build process of your choice.
It is mainly targeted at developers that want to make sure their code provides stable API for its users across different
versions.

See https://revapi.org[Revapi site] for details on how to use it.

== About Revapi API

Revapi API is the generic interface and the main entry point for the (programmatic) users. It provides the API that
its various extensions implement and also the _main_ class for initializing and executing the API analysis.

== Building

This is a maven project, so a simple `mvn install` will suffice.

== Getting in touch

IRC:: #revapi @ freenode
Mailing list:: https://groups.google.com/forum/#!forum/revapi, revapi@googlegroups.com
Issues:: individual subprojects under https://github.com/revapi
Code:: https://github.com/revapi/
