== Revapi API

This module contains the API of Revapi as well as the link:apidocs/org/revapi/Revapi.html[main class] that is used to
instantiate, configure and run the API analysis. It also contains a couple of simplistic implementations of the Revapi
interfaces to get you started with.

Probably more interesting than this short description is the link:../../architecture.html[architecture] of Revapi
which explains the role of individual interfaces found in this module. Additionally you might wanna checkout the
link:project-reports.html[project reports] or link:apidocs[javadoc].

=== Invocation

Revapi can be used in a couple of convenient ways - a link:../revapi-maven-plugin[maven plugin], a
link:../revapi-standalone[cli tool] or even an link:../revapi-ant-task[Ant task]. Please consult the links for more
details about those.

In here we're only going to deal with the invocation of the API analysis using the Java API when Revapi is used as a
library.

First of all, we need to determine what archives we are going to compare. For that Revapi uses the
link:apidocs/org/revapi/API.html[API] class:

```java
API oldApi = API.of(myArchiveV1).supportedBy(v1Dependencies).build();
API oldApi = API.of(myArchiveV2).supportedBy(v2Dependencies).build();
```

NOTE: The `myArchiveV1` and others in the example above are implementations of the
link:apidocs/org/revapi/Archive.html[archive interface]. Revapi API provides a single simple implementation -
link:apidocs/org/revapi/simple/FileArchive.html[FileArchive] which represents a file as a Revapi archive - quite a
useful and fitting thing. There are other implementations, too, though - for example the maven plugin has an
implementation of this, too, which wraps a maven archive in a revapi archive and provides the maven archive's GAV as
the revapi archive's name - quite a useful thing when reporting on what problems were found in which archive.

=== Configuration

Configuration is supplied using https://github.com/jbossas/jboss-dmr[JBoss DMR] which should in theory support
loading the configuration from various formats if enough effort is done on the user's side. Revapi as such has so far
been extensively tested only with JSON data (support for XML has been added only in Revapi 0.8.0 supported by maven
plugin 0.9.0). Even if data was translated into DMR from another format than JSON, the validation
of that data will always be done against a JSON schema that is provided by the extensions.

For details, see the link:apidocs/org/revapi/AnalysisContext.html[AnalysisContext] class (and the way it is supplied
with configuration by the caller) and link:apidocs/org/revapi/configuration/Configurable.html[Configurable] interface
for what is required of the extensions.
