== Package Filter

*Configuration Root*: `revapi.java.filter.packages`

Given Java's lacking modularity (prior to Java9), authors are often forced to make classes that are essentially an
implementation detail of a library public. Such classes are often included in packages like `impl` or `internal` to
hint at their non-public nature.

While Revapi offers the basic filtering capabilities using the
link:../../revapi-basic-features/extensions/filter.html[basic filter], it often is much simpler to exclude classes or
packages like that using this filter (or the link:class-filter.html[class filter]), specifically made for this
purpose (if for nothing else then for the simpler configuration).

By default, all classes in all packages are included. If the include filter is specified, only the classes with packages
matching the include filter are included in the API check. The exclude filter can take out classes in the packages that
would otherwise be included.

It is not possible include classes in package that matches an exclude filter (i.e. if include and exclude filter match
the same package, the classes are not included).

NOTE: Java packages ARE NOT hierarchical even though they are commonly used like they were.

=== Sample Configuration

```javascript
{
  "revapi": {
    "java": {
      "filter": {
        "packages": {
          "regex": true,
          "include": ["com\\.acme\\.api\\..*"]
          "exclude": ["com\\.acme\\.internal"]
        }
      }
    }
  }
}
```

=== Properties
`regex`::
Specifies whether to consider the strings in `exclude` and `include` lists as regular expressions or not. The default
value is `false`, meaning the strings are not considered as regular expressions.
`exclude`::
List of strings representing full package names or regular expressions matching them. Classes with the matching package
names (and the members of those classes) will be excluded from the API check.
`include`::
List of strings representing full package names or regular expressions matching them. Classes with the matching package
names (and the members of those classes) will be included in the API check.

=== Examples

Contrary to intuition, java packages are not hierarchical, even though they have hierarchical names. In Java parlance,
package `com.acme.foo` is a sub-package of `com.acme` but that does not mean that it's enclosing element is
`com.acme`. No, each package is a top level element that does not have any parent elements and which only contains
classes, not other packages.

Therefore if you want to exclude a package and all its sub-packages, you need to use a regular expression
`"com\\.acme(\\..+)?"` which will match the `com.acme` package and any of its sub-packages.
