== Reclassify Transformation

*Configuration Root*: `revapi.reclassify`

Using this extension one can reclassify certain API problems found during the analysis to become something else or
for example reduce their severity.

=== Sample Configuration

```javascript
{
  "revapi" : {
    "reclassify" : [
    {
      "regex" : false,
      "code" : "PROBLEM_CODE",
      "old" : "FULL_REPRESENTATION_OF_THE_OLD_ELEMENT",
      "new" : "FULL_REPRESENTATION_OF_THE_NEW_ELEMENT",
      "classify" : {
        "NEW_COMPATIBILITY_TYPE": "NEW_SEVERITY",
        "NEW_COMPATIBILITY_TYPE_2": "NEW_SEVERITY_2",
      }
    },
    ...
    ]
  }
}
```

=== Properties

`regex`::
If `true` (the default is `false`), the `code`, `old` and `new` values are understood to be java regular expressions.
`code`::
Specifies the API problem code to reclassify. This is property mandatory.
`old`::
Specifies the old element of the problem. Only if the problem's old element matches this, the reclassification takes
place. This property is optional.
`new`::
Specifies the new element of the problem. Only if the problem's new element matches this, the reclassification takes
place. This property is optional.
`classify`::
Specifies the new classification matrix of the problem. The keys are compatibility types, i.e. one of `SOURCE`,
`BINARY`, `SEMANTIC` or `OTHER` and severities are one of `NON_BREAKING`, `POTENTIALLY_BREAKING` or `BREAKING`.

=== Example

By specifying the following configuration:

```javascript
{
    "revapi" : {
        "reclassify" : {
            "code" : "java.class.added",
            "new" : "class my.great.app.ForbiddenClass",
            "classify" : {
                "BINARY" : "BREAKING"
            }
        }
    }
}
```

it will be an API error if the class `my.great.app.ForbiddenClass` appears in the new version of a java library (granted
this rule is somewhat weird and maybe not entirely useful, but it illustrates the purpose - you can come up with
different policies that your code should follow and enforce them through such rules).
