== Downloads

Revapi doesn't maintain its own downloadable archives because all the artifacts are stored in the Maven Central
repository.

Here are the links to the latest versions of the individual artifacts.

NOTE: Please allow a day or so for the links to start working after a release. That is the delay between the actual
release and the time the artifacts are replicated into Maven Central. If you'd like to download an older version of the
artifacts, use the link to "All Versions" and pick the one you like.

|===
|Name|Artifact|Version|Release Date|Link|All Versions

|Revapi API
|`org.revapi:revapi`
|+++<div id="version-org.revapi-revapi"></div>+++
|+++<div id="release-date-org.revapi-revapi"></div>+++
|+++<a id="link-org.revapi-revapi">here</a>+++
|+++<a id="all-link-org.revapi-revapi">here</a>+++

|Revapi Maven Plugin
|`org.revapi:revapi-maven-plugin`
|+++<div id="version-org.revapi-revapi-maven-plugin"></div>+++
|+++<div id="release-date-org.revapi-revapi-maven-plugin"></div>+++
|+++<a id="link-org.revapi-revapi-maven-plugin">here</a>+++
|+++<a id="all-link-org.revapi-revapi-maven-plugin">here</a>+++

|Revapi Ant Task
|`org.revapi:revapi-ant-task`
|+++<div id="version-org.revapi-revapi-ant-task"></div>+++
|+++<div id="release-date-org.revapi-revapi-ant-task"></div>+++
|+++<a id="link-org.revapi-revapi-ant-task">here</a>+++
|+++<a id="all-link-org.revapi-revapi-ant-task">here</a>+++

|Revapi Standalone CLI
|`org.revapi:revapi-standalone`
|+++<div id="version-org.revapi-revapi-standalone"></div>+++
|+++<div id="release-date-org.revapi-revapi-standalone"></div>+++
|+++<a id="link-org.revapi-revapi-standalone">here</a>+++
|+++<a id="all-link-org.revapi-revapi-standalone">here</a>+++

|Revapi Basic Features Extension
|`org.revapi:revapi-basic-features`
|+++<div id="version-org.revapi-revapi-basic-features"></div>+++
|+++<div id="release-date-org.revapi-revapi-basic-features"></div>+++
|+++<a id="link-org.revapi-revapi-basic-features">here</a>+++
|+++<a id="all-link-org.revapi-revapi-basic-features">here</a>+++

|Revapi Java Extension
|`org.revapi:revapi-java`
|+++<div id="version-org.revapi-revapi-java"></div>+++
|+++<div id="release-date-org.revapi-revapi-java"></div>+++
|+++<a id="link-org.revapi-revapi-java">here</a>+++
|+++<a id="all-link-org.revapi-revapi-java">here</a>+++

|Revapi Java Extension SPI
|`org.revapi:revapi-java-spi`
|+++<div id="version-org.revapi-revapi-java-spi"></div>+++
|+++<div id="release-date-org.revapi-revapi-java-spi"></div>+++
|+++<a id="link-org.revapi-revapi-java-spi">here</a>+++
|+++<a id="all-link-org.revapi-revapi-java-spi">here</a>+++

|Revapi Text Reporter Extension
|`org.revapi:revapi-reporter-text`
|+++<div id="version-org.revapi-revapi-reporter-text"></div>+++
|+++<div id="release-date-org.revapi-revapi-reporter-text"></div>+++
|+++<a id="link-org.revapi-revapi-reporter-text">here</a>+++
|+++<a id="all-link-org.revapi-revapi-reporter-text">here</a>+++

|Revapi BOM
|`org.revapi:revapi-bom`
|+++<div id="version-org.revapi-revapi-bom"></div>+++
|+++<div id="release-date-org.revapi-revapi-bom"></div>+++
|+++<a id="link-org.revapi-revapi-bom">here</a>+++
|+++<a id="all-link-org.revapi-revapi-bom">here</a>+++

|===

[pass]
++++
  <script type="text/javascript">
window.addEventListener("load", function() {
    function fillIn(groupId, artifactId, downloadableType) {
        var url = "modules/" + artifactId + "/index.html"
        $.ajax(url, {
          "cache": false,
          "dataType": "html"
        }).done(function(data) {
            var doc = $("<div/>").append(data);

            var v = doc.find(".projectVersion").text().substring("Version: ".length)
            var date = doc.find(".publishDate").text().substring("Last Published: ".length)

            var dg = groupId.replace(/\./g, "")
            var da = artifactId.replace(/\./g, "")

            document.getElementById("version-" + dg + "-" + da).textContent = v;
            document.getElementById("release-date-" + dg + "-" + da).textContent = date;

            var gp = groupId.replace(/\./g, "/")
            var ap = artifactId.replace(/\./g, "/")

            var link = document.getElementById("link-" + dg + "-" + da);
            link.href =
                "http://search.maven.org/remotecontent?filepath=" + gp + "/" + ap + "/" +
                v + "/" + artifactId + "-" + v + downloadableType;

            var allLink = document.getElementById("all-link-" + dg + "-" + da);
            allLink.href = "http://search.maven.org/#search|gav|1|g%3A%22" + groupId + "%22%20AND%20a%3A%22"
             + artifactId + "%22"
        }).fail(function (data, status) {
            console.log("URL failed with status " + status + ": " + url)
        })
    }

    fillIn("org.revapi", "revapi", ".jar")
    fillIn("org.revapi", "revapi-ant-task", ".jar")
    fillIn("org.revapi", "revapi-basic-features", ".jar")
    fillIn("org.revapi", "revapi-bom", ".jar")
    fillIn("org.revapi", "revapi-java", ".jar")
    fillIn("org.revapi", "revapi-java-spi", ".jar")
    fillIn("org.revapi", "revapi-maven-plugin", ".jar")
    fillIn("org.revapi", "revapi-reporter-text", ".jar")
    fillIn("org.revapi", "revapi-standalone", "-standalone.zip")
})
</script>
++++
