== Getting Started

Revapi can be used in 3 ways. Either as a standalone java program, using its maven plugin during build or as an embedded
library.

=== Standalone Usage

First you need to download the standalone distribution of Revapi, say `revapi-standalone-{version}.zip`. Now you have to:

====
unzip revapi-standalone-{version}.zip
cd revapi-standalone-{version}
====

Your installation is now ready. To start using it, you can simply invoke

----
./revapi.sh
----

(or if you're unfortunate enough to be on windows)

----
revapi.bat
----

and you will be presented with the usual usage information.

----
revapi.sh [-u|-h] -e <GAV>[,<GAV>]* -o <FILE>[,<FILE>]* -n <FILE>[,<FILE>]* [-s <FILE>[,<FILE>]*] [-t <FILE>[,<FILE>]*]
          [-D<CONFIG_OPTION>=<VALUE>]* [-c <FILE>[,<FILE>]*] [-r <DIR>]

          -u
          -h
          --usage
          --help
              Prints this message and exits.
          -e
          --extensions=<GAV>[,<GAV>]*
              Comma-separated list of maven GAVs of revapi extensions.
          -o
          --old=<FILE>[,<FILE>]*
             Comma-separated list of files of the old version of API
          -a
          --old-gavs=<FILE>[,<FILE>]*
             Comma-separated list of GAVs of the old version of API
          -s
          --old-supplementary=<FILE>[,<FILE>]*
             Comma-separated list of files that supplement the old version of API
          -n
          --new=<FILE>[,<FILE>]*
             Comma-separated list of files of the new version of API
          -b
          --new-gavs=<FILE>[,<FILE>]*
             Comma-separated list of GAVs of the new version of API
          -t
          --new-supplementary=<FILE>[,<FILE>]*
             Comma-separated list of files that supplement the new version of API
          -D
             A key-value pair representing a single configuration option of revapi or one of the loaded extensions
          -c
          --config-files=<FILE>[,<FILE>]*
             Comma-separated list of configuration files in Java properties format.
          -d
          --cache-dir=<DIR>
             The location of local cache of extensions to use to locate artifacts. Defaults to 'extensions' directory
             under revapi installation dir.

You can specify the old API either using -o and -s where you specify the filesystem paths to the archives and
supplementary archives respectively or you can use -a to specify the GAVs of the old API archives and the supplementary
archives (i.e. their transitive dependencies) will be determined automatically using Maven. But you cannot do both
obviously.

Of course you can do the same for the new version of the API by using -n and -t for file paths or -b for GAVs.
----

An invocation of Revapi could look like this:

----
./revapi.sh -extensions=org.revapi:revapi-java:{version},org.revapi:revapi-text-reporter:{version} \
   --old=my-lib-0.1.0.jar --new=my-lib-0.2.0.jar -D revapi.reporter.text.minSeverity=BREAKING
----

The supplementary archives, in case of java, are additional jars defining classes that classes in your "main" jar "leak"
into the API, i.e. if some of your classes inherit from one defined in the additional jar, or if one of your API
method's return type or parameter comes from the additional jar.

Different extensions might define different configuration options that you might supply to them using either the `-D`
command line parameter or they can be read from a java property file(s) specified by the `-c` option.

=== Maven

Revapi's main purpose is to track API changes between releases. This is ideally done during build and so the maven
integration is essential.

The basic usage of the Revapi's maven plugin is quite simple. In your `pom.xml`, do:

[source,xml]
----
<build>
    ...
    <plugins>
        ...
        <plugin>
            <groupId>org.revapi</groupId>
            <artifactId>revapi-maven-plugin</artifactId>
            <version>{version}</version>
            <dependencies>
                <dependency>
                    <groupId>org.revapi</groupId>
                    <artifactId>revapi-java</artifactId>
                    <version>{version}</version>
                </dependency>
                ...
            </dependencies>
            <executions>
                <execution>
                    <id>check</id>
                    <goals><goal>check</goal><goals>
                </execution>
            </executions>
        </plugin>
        ...
    </plugins>
    ...
</build>
----

By default, Revapi only bundles the <<extension-basic.adoc#, basic extensions>> so in order to check your java code,
you need to add the Revapi's java extension as a dependency to the maven plugin.

For more detailed info, check the maven plugin's link:../generated/revapi-maven-plugin/plugin-info.html[site].

=== Ant

There is also an Ant task to invoke Revapi analysis on arbitrary archives.
The task implicitly supports the <<extension-basic.adoc#, basic extensions>>
but other extensions need to be added.

The following attributes are supported:

|====
|`oldArchives`|The `FileSet` of archives of the old version of the API
|`oldSupplementaryArchives`|The `FileSet` of archives that support the old API (i.e. dependencies)
|`newArchives`|The `FileSet` of archives of the new version of the API
|`newSupplementaryArchives`|The `FileSet` of archives that support the new API (i.e. dependencies)
|`revapiClassPath`|A `Path` to additional extensions to use with Revapi
|`configuration`|A JSON string with the Revapi configuration
|`breakingSeverity`|The minimal severity of differences that will be reported
|====

An example for checking Java code:

[source,xml]
----
<target name="api-check">
  <taskdef name="revapi" classname="org.revapi.ant.RevapiTask" classpath="lib/revapi-ant-task-{version}.jar"/>
  <revapi>
    <oldArchives file="mylib-1.0.jar"/>
    <newArchives file="mylib-1.1.jar"/>
    <revapiClassPath>
      <pathelement location="lib/revapi-java-{version}-uber.jar"/>
    </revapiClassPath>
  </revapi>
</target>
----

Notice the use of the "uber" jar for the java extension. The uber jar of
the java extension contains its dependencies (excluding the revapi API
itself which is considered provided).

=== Embedding

[source,java]
----
Revapi revapi = Revapi.builder().withAllExtensionsFromThreadContextClassLoader().build();

AnalysisContext analysisContext = AnalysisContext.builder()
    .withOldAPI(API.of(...))
    .withNewAPI(API.of(...))
    .withConfigurationFromJSON("json").build();

revapi.analyze(analysisContext);
----

For more details, see link:../generated/index.html[javadoc].
